# Generated by Django 3.0.8 on 2020-07-31 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(db_index=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_credit', models.IntegerField()),
                ('max_credit', models.IntegerField()),
                ('min_age_borrower', models.IntegerField()),
                ('max_age_borrower', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('approved', 'одобрено'), ('rejected', 'отказ')], max_length=12, null=True)),
                ('rejection_reason', models.TextField(max_length=1000, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='v1.Borrower')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='v1.Program')),
            ],
        ),
    ]
